# Generated by Django 3.2.15 on 2023-02-21 11:06

from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "update_previous_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    (foodcartapp.models.OrderStatus["SUBMITTED"], "Отправлен"),
                    (foodcartapp.models.OrderStatus["IN_PROGRESS"], "Готовится"),
                    (foodcartapp.models.OrderStatus["IN_DELIVERY"], "Доставляется"),
                    (foodcartapp.models.OrderStatus["DELIVERED"], "Доставлен"),
                ],
                default="SUBMITTED",
                max_length=10,
                verbose_name="Статус заказа",
            ),
        ),
    ]
