# Generated by Django 3.2.15 on 2023-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0005_order_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="call_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата звонка"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата доставки"
            ),
        ),
    ]
