# Generated by Django 3.2.15 on 2023-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0007_alter_order_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Наличными при доставке"),
                    ("ONLINE", "On-line, при создании"),
                ],
                db_index=True,
                default="CASH",
                max_length=6,
                verbose_name="Тип оплаты",
            ),
        ),
    ]
