# Generated by Django 3.2.15 on 2023-02-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0008_order_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="executing_restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="foodcartapp.restaurant",
                verbose_name="Ресторан, готовящий заказ",
            ),
        ),
    ]
