# Generated by Django 3.2.15 on 2023-02-21 08:00

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0037_auto_20210125_1833"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="foodcartapp.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказанный товар",
                "verbose_name_plural": "Заказанные товары",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Номер телефона"
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="Адрес доставки")),
                (
                    "ordered_items",
                    models.ManyToManyField(
                        to="foodcartapp.OrderedItem", verbose_name="Заказанные товары"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
