# Generated by Django 3.2.15 on 2023-02-21 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_auto_20230221_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordereditem",
            name="product_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Цена товара",
            ),
            preserve_default=False,
        ),
    ]
